### ISSUE TITLE
Floating on Release() (seems WorldTools.FindEmptyTerrainPosition issue)

### ISSUE THREAD

**Issue by FinneyDe** [cen-mod/CarrierSystem#11] opened 2023-11-27 22:50 UTC
First off the scripts above me in a lot of regards so don't take this as nit-picking, and I just started toying around with Arma modding today.

CEN_CarrierSystem_Helper.c

changed Carry method 
`//carrier.AddChild(helper, carrier.GetBoneIndex("Spine5"));  
carrier.AddChild(helper, carrier.GetAnimation().GetBoneIndex("Spine5"));`

Release Method I made a bit more crude changes but didn't seem to have the same floating above by 30M and slowly dropping.  I understand the attempt with FindEmpty is to make sure its a safe placement.  Under the carrier is mostly safe, is my logic.
Again, I don't think this is your code I think its FindEmptyTerrainPosition (seems removing wounded from vehicles also creates similar behavior).

````
 [RplRpc(RplChannel.Reliable, RplRcver.Server)]
	void Release()
	{
		SCR_CompartmentAccessComponent compartmentAccessComponent = SCR_CompartmentAccessComponent.Cast(m_eCarried.FindComponent(SCR_CompartmentAccessComponent));
		if (!compartmentAccessComponent)
			return;


		vector carrierPosition[4];
		m_eCarried.GetTransform(carrierPosition);	
		compartmentAccessComponent.MoveOutVehicle(-1, carrierPosition);
		
		m_bMarkedForDeletion = true;
		// Clean up later since otherwise the carried player gets deleted as well...
		GetGame().GetCallqueue().CallLater(CleanUp, CLEANUP_TIMEOUT, false);
	
	}
'

Figured I'd at least report my findings.  Great mod regardless!

**Comment by Kexanone** [comment] 2023-11-28 11:48
Thanks for your report, but I have reservations about your findings.
There is evidence against `WorldTools.FindEmptyTerrainPosition` being the issue:
- The issue is not reproducible in the workbench (even with peer tool). Which suggests to me that the coordinate returned by `WorldTools.FindEmptyTerrainPosition` is fine.
- As you mentioned, the issue can also be observed when removing casualties from vehicles. You can check the code in `SCR_RemoveCasualtyUserAction.PerformAction` and see that `WorldTools.FindEmptyTerrainPosition` is not used there.

As I mentioned, I don't think the issue can be reproduced in the workbench and hence why any tests there are meaningless.

**Comment by Kexanone** [comment] 2024-01-17 21:42
Closed asdeprecated `GetBoneIndex` method got replaced in latest built

**Closed by Kexanone** 2024-01-17 21:42 UTC
